# fly.toml app configuration file generated for neonetrek-iad on 2026-03-06T21:47:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neonetrek-iad'
primary_region = 'iad'

[build]

[env]
  WS_PORT = '3000'

[[mounts]]
  source = 'netrek_data'
  destination = '/opt/netrek/var'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[checks]
  [checks.health]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '256mb'
